### ISSUE TITLE
-u flag : [Error] Something went wrong adding domain users to rules.

### ISSUE THREAD

**Issue by hackandbackpack** [SnaffCon/Snaffler#153]
Have been attempting to get snaffler to pull a list of domain users and add them to the rules list, but it doesn't seem to function correctly.  I tested in two different environments to make sure it wasn't an isolated issue but had the same error running in both. After the error Snaffler does continue to run sucessfully ... but it doesn't include the rule changes including usernames pulled from AD.

PS C:\Users\student\Desktop\Tools\Snaffler> .\Snaffler.exe -s -a -m . -u -v trace
[THINKLIFY\student@student] 2024-10-03 20:29:06Z [Info] Parsing args...
[THINKLIFY\student@student] 2024-10-03 20:29:06Z [Degub] Requested verbosity level: trace
[THINKLIFY\student@student] 2024-10-03 20:29:06Z [Degub] Enabled logging to stdout.
[THINKLIFY\student@student] 2024-10-03 20:29:06Z [Degub] Enabled use of domain user accounts in rules.
[THINKLIFY\student@student] 2024-10-03 20:29:06Z [Degub] Mirroring matched files to path .
[THINKLIFY\student@student] 2024-10-03 20:29:07Z [Info] Parsed args successfully.
[THINKLIFY\student@student] 2024-10-03 20:29:07Z [Degub] Set verbosity level to trace.
**[THINKLIFY\student@student] 2024-10-03 20:29:07Z [Info] Getting interesting users from AD.
[THINKLIFY\student@student] 2024-10-03 20:29:07Z [Trace] Getting current domain from user context.**
[THINKLIFY\student@student] 2024-10-03 20:29:07Z [Trace] Adding Administrator to target list because it had adminCount=1.
**[THINKLIFY\student@student] 2024-10-03 20:29:07Z [Trace] System.ArgumentNullException: Value cannot be null.
Parameter name: source**
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   at SnaffCore.ActiveDirectory.AdData.SetDomainUsers()`
[THINKLIFY\student@student] 2024-10-03 20:29:07Z [Trace] Adding jfox to target list because password does not expire,  probably service account.
[THINKLIFY\student@student] 2024-10-03 20:29:07Z [Trace] System.ArgumentNullException: Value cannot be null.
Parameter name: source
[THINKLIFY\student@student] 2024-10-03 20:29:07Z [Trace] Adding jason to target list because it had adminCount=1.
[THINKLIFY\student@student] 2024-10-03 20:29:07Z [Trace] System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Contains[TSource](IEnumerable`1 source, TSource value, IEqualityComparer`1 comparer)
   at SnaffCore.ActiveDirectory.AdData.SetDomainUsers()
**[THINKLIFY\student@student] 2024-10-03 20:29:07Z [Error] Something went wrong adding domain users to rules.**

**Comment by l0ss** [comment]
it's possible that other changes broke this functionality - I'll have a look at it and see if i can figure out what's happened.
