### ISSUE TITLE
The value '2097151' is not valid for this usage of the type FileSystemRights

### ISSUE THREAD

**Issue by ss23** [SnaffCon/Snaffler#59]
```
[REDACTED\ss23@XXX] 2021-09-21 13:14:45Z [Error] System.ArgumentOutOfRangeException: The value '2097151' is not valid for this usage of the type FileSystemRights.
Parameter name: fileSystemRights
   at System.Security.AccessControl.FileSystemAccessRule.AccessMaskFromRights(FileSystemRights fileSystemRights, AccessControlType controlType)
   at SnaffCore.Classifiers.EffectiveAccess.EffectiveAccess.GetEffectiveAccess(FileSystemInfo item, IdentityReference2 id, String serverName) in Z:\tcfox On My Mac\Source\Repos\github.com\SnaffCon\Snaffler\SnaffCore\Classifiers\EffectiveAccess\EffectiveAccess.cs:line 113
   at SnaffCore.Classifiers.EffectiveAccess.EffectivePermissions.GetEffectivePermissions(FileSystemInfo filesysInfo, String username) in Z:\tcfox On My Mac\Source\Repos\github.com\SnaffCon\Snaffler\SnaffCore\Classifiers\EffectiveAccess\EffectiveAccess.cs:line 88
```

No idea what is causing it :)

**Comment by l0ss** [comment]
Fixed in ACLCrimes
