### ISSUE TITLE
Permission errors should not be shown to users if a folder/file is not readable

### ISSUE THREAD

**Issue by ss23** [SnaffCon/Snaffler#60]
I expect Snaffler to silently ignore errors related to not being able to read a particular file/folder, however, I received this error when running:

```
[REDACTED\ss23@REDACTED] 2021-09-21 13:14:16Z [Error] System.UnauthorizedAccessException: (5) Access is denied: [\\?\UNC\REDACTED\REDACTED$]
   at Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   at Alphaleonis.Win32.Filesystem.File.CreateFileCore(KernelTransaction transaction, String path, ExtendedFileAttributes attributes, FileSecurity fileSecurity, FileMode fileMode, FileSystemRights fileSystemRights, FileShare fileShare, Boolean checkPath, PathFormat pathFormat)
   at Alphaleonis.Win32.Filesystem.File.GetAccessControlCore[T](Boolean isFolder, String path, AccessControlSections includeSections, PathFormat pathFormat)
   at Alphaleonis.Win32.Filesystem.DirectoryInfo.GetAccessControl(AccessControlSections includeSections)
   at SnaffCore.Classifiers.EffectiveAccess.FileSystemSecurity2..ctor(FileSystemInfo item) in Z:\tcfox On My Mac\Source\Repos\github.com\SnaffCon\Snaffler\SnaffCore\Classifiers\EffectiveAccess\EffectiveAccess.cs:line 708
   at SnaffCore.Classifiers.EffectiveAccess.EffectiveAccess.GetEffectiveAccess(FileSystemInfo item, IdentityReference2 id, String serverName) in Z:\tcfox On My Mac\Source\Repos\github.com\SnaffCon\Snaffler\SnaffCore\Classifiers\EffectiveAccess\EffectiveAccess.cs:line 113
   at SnaffCore.Classifiers.EffectiveAccess.EffectivePermissions.GetEffectivePermissions(FileSystemInfo filesysInfo, String username) in Z:\tcfox On My Mac\Source\Repos\github.com\SnaffCon\Snaffler\SnaffCore\Classifiers\EffectiveAccess\EffectiveAccess.cs:line 88
   at SnaffCore.Classifiers.EffectiveAccess.EffectivePermissions.CanRw(FileSystemInfo filesysInfo) in Z:\tcfox On My Mac\Source\Repos\github.com\SnaffCon\Snaffler\SnaffCore\Classifiers\EffectiveAccess\EffectiveAccess.cs:line 39
```

**Comment by l0ss** [comment]
Fix for this is present in ACLCrimes branch
