### ISSUE TITLE
Issue with Get-DomainDFSShareV1

### ISSUE THREAD

**Issue by r35pect** [SnaffCon/Snaffler#99]
`Get-DomainDFSShareV1 error : System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.BitConverter.ToUInt32(Byte[] value, Int32 startIndex)
   at SnaffCore.ActiveDirectory.DfsFinder.Parse_Pkt(Byte[] Pkt)
   at SnaffCore.ActiveDirectory.DfsFinder.Get_DomainDFSShareV1(DirectorySearch _directorySearch)
`

Not sure what is going on here. Is this a parsing issue on Snaffler's side?

**Comment by l0ss** [comment]
Could be - but I'd need more information about the domain to be able to diagnose it - do you still have access to the domain where this was happening?

**Comment by l0ss** [comment]
closing - will reopen if you can provide some more debug info
